### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by wparkermackenzie** [ARMmbed/lorawan-fota-demo#4]
Hello,
I have a few questions concerning the status of this project. I have outlined them below.

1. How does this implementation differ from the current state of the standard at the LoRa alliance? 
2. What is the time frame of this project being an officially released mbed library?
3. Can you share your plans for abstracting the firmware update mechanism from the underlying hardware and network server?
4. What is the time frame for supporting patch updates?

Thank you in advance,
Parker MacKenzie

**Comment by janjongboom** [comment]
Hi Parker,

1. There are a couple of changes regarding packet formats, and we don't support the new multi-packet protocol yet. If you have access to the specifications updating them shouldn't be too hard.
2. When multicast and data fragmentation specs are released we'll be updating this library to the latest specs.
3. Yes, we'll switch over to our [IETF SUIT](https://datatracker.ietf.org/wg/suit/about/) compatible update client which we also use for Mbed Cloud; probably when 2) happens. This will be integrated with the Mbed OS LoRaWAN stack and can run on any board that has FlashIAP implemented.
4. Delta updates are already supported in the current release.

**Comment by wparkermackenzie** [comment]
Thank you Jan.
